# Makefile for "CFCSS_MOD.cpp" pass

# Path to top level of LLVM hierarchy
LEVEL = ../../../..

# Name of the library to build
LIBRARYNAME = CFCSS_NEW_XOR_SBL64

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common